// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  bendo: dynamic(() => import("./Bendo")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  navbar: dynamic(() => import("./Navbar")),
  showogg: dynamic(() => import("./Showoff")),
  sustainability: dynamic(() => import("./Sustainability")),
};
